/** Public glossary API. */

export {
	DATABASE_NAME,
	DATABASE_VERSION,
	GLOSSARY_DATABASE_NAME,
	GLOSSARY_DATABASE_VERSION,
	type GlossaryOpenResult,
	INDEX_PAIR,
	INDEX_PAIR_SOURCE,
	INDEX_TARGET,
	openGlossaryDatabase,
	TERMS_STORE,
	transactionAsPromise,
	VERSIONS_STORE,
} from "./db";
export { GlossaryAutomaton, matchGlossaryTerms } from "./matcher";
export {
	defaultCaseSensitive,
	type ExportFormat,
	type GlossaryImportReport,
	type GlossaryMatch,
	type GlossaryTerm,
	type GlossaryTermInput,
	type GlossaryTermPatch,
	type GlossaryValidationResult,
	type GlossaryVersionProvider,
	type ImportConflictStrategy,
	isCjkLanguage,
	isLatinLanguage,
	type LanguagePair,
	MAX_GLOSSARY_FIELD_LENGTH,
	type NormalizedGlossaryTermInput,
	newTermId,
	normalizeLanguage,
	normalizeSource,
	pairKey,
	termAppliesToPair,
	termKey,
	toExportableTerm,
	validateStoredTerm,
	validateTermInput,
} from "./model";
export {
	addTerm,
	bulkAddTerms,
	bulkUpsertTerms,
	clearTerms,
	createGlossaryStore,
	createTerm,
	deleteTerm,
	exportTerms,
	type GlossaryExportResult,
	type GlossaryResult,
	type GlossaryStore,
	type GlossaryStoreOptions,
	type GlossaryWriteResult,
	getGlossaryVersion,
	getTerm,
	glossaryStore,
	importTerms,
	listTerms,
	matchGlossary,
	matchTerms,
	removeTerm,
	store,
	updateTerm,
} from "./store";
export {
	escapeCsvField,
	GLOSSARY_CSV_COLUMNS,
	GLOSSARY_EXPORT_VERSION,
	type ParsedGlossaryPayload,
	parseCsv,
	parseGlossaryPayload,
	serializeGlossary,
	toCsv,
	toJson,
} from "./transfer";
